# Root Hydra config.
#
# Usage:
#   python run.py experiment=main_results_ami
#   python run.py experiment=main_results_ami trainer.max_epochs=2
#   python run.py mlflow.tracking_uri=http://localhost:5000

defaults:
  - experiment: smoke
  - mlflow: dagshub
  - logging: default
  - _self_

hydra:
  run:
    dir: /tmp/hydra/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: /tmp/hydra-sweeps/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  output_subdir: null
  job_logging:
    root:
      handlers: []
    disable_existing_loggers: false
