# configs/config.yaml
defaults:
  - data: ami               # configs/data/ami.yaml dosyasını seç
  - model: mlp_pool         # configs/model/mlp_pool.yaml dosyasını seç
  - trainer: default        # configs/trainer/default.yaml dosyasını seç
  - _self_                  # Kendi içindeki override'lara öncelik ver

# İstersen genel proje ayarlarını buraya yazabilirsin
project_name: "ASR_Model_Selector"
seed: 42